# Generated by Django 4.0.1 on 2022-01-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
